import Foundation
import ShotModel
import XCTest
@testable import SOPKit

/// Guards against the three ways a generation came back structurally valid and
/// semantically empty. All three shipped, and all three were reported together:
/// "SOP generation failed" about a quarter of the time, and an Overview that
/// said only "Placeholder".
final class UnderproductionTests: XCTestCase {

    // MARK: The schema must make an empty plan unrepresentable

    /// `steps: []` satisfied the old schema perfectly, so the model could return
    /// a conforming plan with no work in it and the failure was only caught after
    /// the fact by `SopService`'s `wroteAnyStep` guard. Constrained decoding
    /// cannot emit an empty array with this set.
    func testStepsCannotBeEmpty() {
        let schema = sopEditJSONSchema()
        let steps = schema["properties"].flatMap { ($0 as? [String: Any])?["steps"] as? [String: Any] }
        XCTAssertEqual(steps?["minItems"] as? Int, 1, "steps must declare minItems: 1")
    }

    /// The API accepts ONLY 0 and 1 for `minItems`, and rejects `minLength`,
    /// `maxItems`, `minimum`/`maximum` and `pattern` outright. shotAI speaks to
    /// the API directly with no SDK, so there is no client-side transform to
    /// strip an unsupported keyword — one would 400 every request rather than
    /// being quietly dropped. This walks the whole schema rather than the one
    /// field, so a future constraint added anywhere is caught here and not in
    /// production.
    func testSchemaUsesNoUnsupportedKeywords() {
        let banned = ["minLength", "maxLength", "maxItems", "minimum", "maximum", "multipleOf", "pattern"]
        var found: [String] = []
        func walk(_ any: Any, path: String) {
            guard let dict = any as? [String: Any] else {
                if let arr = any as? [Any] {
                    for (i, v) in arr.enumerated() { walk(v, path: "\(path)[\(i)]") }
                }
                return
            }
            for k in banned where dict[k] != nil { found.append("\(path).\(k)") }
            if let m = dict["minItems"] as? Int, m != 0 && m != 1 {
                found.append("\(path).minItems=\(m) (only 0 and 1 are accepted)")
            }
            for (k, v) in dict { walk(v, path: "\(path).\(k)") }
        }
        walk(sopEditJSONSchema(), path: "root")
        XCTAssertTrue(found.isEmpty, "unsupported schema keywords would 400 the request: \(found)")
    }

    // MARK: The prompt must not name the filler words

    /// Naming a bad value teaches it. The word "placeholder" was moved off the
    /// title VALUE after Claude returned it as the title, then reintroduced as a
    /// negative example — and it came back in the `intro` instead, which that
    /// sentence never covered. Constrain positively; name nothing.
    func testTheAutoTitleInstructionNamesNoFillerWords() {
        let name = "Project 2026/08/19 12:41:16"
        XCTAssertTrue(ProjectStore.isAutoGeneratedTitle(name), "fixture must hit the auto branch")
        let header = titleInstruction(currentName: name, isAutoGenerated: true)
        XCTAssertTrue(header.contains("generated by the app from a timestamp"),
                      "expected the auto-generated-title branch to be the one under test")
        for word in ["placeholder", "untitled", "\"SOP\"", "\"Project\""] {
            XCTAssertFalse(header.lowercased().contains(word.lowercased()),
                           "the prompt names \"\(word)\", which is how it ends up in the output")
        }
    }

    // MARK: Null must be an available answer for the overview

    /// The schema always allowed `intro: null`, but the prompt only ever said
    /// "you may add" one — so a model with nothing to say filled it instead of
    /// omitting it, which is how an Overview reading "Placeholder" happens.
    func testTheSystemPromptOffersNullAsAnAnswerForIntro() {
        let p = BASE_SYSTEM_PROMPT
        XCTAssertTrue(p.contains("`intro` to null"), "the prompt must say null is a legitimate answer")
        XCTAssertTrue(p.lowercased().contains("filler"), "and must say filler is worse than none")
    }

    // MARK: A plan that would change nothing must fail, not apply silently

    /// The failure actually reported as "it returned only an overview".
    ///
    /// A plan full of well-written steps whose `stepNumber`s match no real step
    /// used to pass the content-only guard, apply to nothing, and leave the user
    /// with a new title and overview and NO error. Driven end to end through the
    /// real streaming path so the guard is tested where it lives.
    ///
    /// The numbering the assembler shows Claude counts author text blocks too, so
    /// the only screenshot in a two-item project is "Screenshot step 2", not 1. A
    /// model that numbers the screenshots 1..N instead lands outside the map
    /// entirely.
    func testAPlanMatchingNoRealStepIsRejected() async throws {
        let (store, path, dir) = try await makeProject(shots: 1)
        try await store.mutate(at: path) { m in
            m.steps.insert(ProjectStep(id: "t0", order: 0, kind: .text, screenshot: "",
                                       trigger: .hotkey, heading: "Before you start",
                                       body: "context"), at: 0)
            ProjectStore.renumber(&m.steps)
        }
        let manifest = try await store.openProject(at: path).manifest

        // Real content, but numbered 1 — the screenshot is step 2.
        let json = #"{"title":"A Real Title","intro":{"heading":"Overview","body":"words"},"steps":[{"stepNumber":1,"caption":"Click Save","body":"Press it.","sectionHeading":null,"sectionBody":null}]}"#
        let svc = SopService(
            client: ClaudeClient(transport: MockTransport(streamHandler: { _ in
                (sseLines(json: json), ResponseHead(status: 200))
            })),
            keyStore: StubKeyStore())

        do {
            _ = try await svc.generate(dir: dir, manifest: manifest,
                                       settings: SopSettings(), onProgress: { _ in })
            XCTFail("a plan that cannot change any step must not be returned as a success")
        } catch let e as ClaudeError {
            // The numbering case specifically: instructions WERE written, they
            // just matched nothing. The two causes carry opposite advice, so the
            // test pins which one rather than only that it failed.
            XCTAssertEqual(e, .incomplete(wroteNothing: false),
                           "expected the stepNumber-mismatch failure, got \(e)")
        }
    }

    /// The control: the SAME content, numbered correctly, must succeed — or the
    /// guard above is just rejecting everything.
    func testACorrectlyNumberedPlanIsAccepted() async throws {
        let (store, path, dir) = try await makeProject(shots: 1)
        try await store.mutate(at: path) { m in
            m.steps.insert(ProjectStep(id: "t0", order: 0, kind: .text, screenshot: "",
                                       trigger: .hotkey, heading: "Before you start",
                                       body: "context"), at: 0)
            ProjectStore.renumber(&m.steps)
        }
        let manifest = try await store.openProject(at: path).manifest

        let json = #"{"title":"A Real Title","intro":null,"steps":[{"stepNumber":2,"caption":"Click Save","body":"Press it.","sectionHeading":null,"sectionBody":null}]}"#
        let svc = SopService(
            client: ClaudeClient(transport: MockTransport(streamHandler: { _ in
                (sseLines(json: json), ResponseHead(status: 200))
            })),
            keyStore: StubKeyStore())

        let plan = try await svc.generate(dir: dir, manifest: manifest,
                                          settings: SopSettings(), onProgress: { _ in })
        XCTAssertEqual(plan.steps.first?.caption, "Click Save")
    }
}
