// GENERATED by Scripts/gen-brand.swift from contract/brand.json — DO NOT EDIT.
// contract sha256: c945d17c1c348c8007d16cdd6dc47be7040de47f7071932dfc5d413e6baa64ff
//
// Change a colour in contract/brand.json and regenerate; the same file drives
// src/shared/brand-colors.generated.ts in Armadillon44/shotAI, so the two
// platforms cannot disagree about a value neither of them owns.
//
// The struct, its documentation and everything about how these are CONSUMED
// live in BrandPalette.swift, by hand. Only the table is generated.

public extension BrandPalette {
    static let shotAI = BrandPalette(
        radii: BrandRadii(panel: 12, card: 10, figure: 8, control: 6, chip: nil),
        fontFamily: nil,
        fontPostScriptName: nil,
        fontFallbacks: ["-apple-system", "\"Segoe UI\"", "Roboto", "Helvetica", "Arial", "sans-serif"],
        accent: Pair(0x6344F1, 0x9A8BF7),
        accentPress: Pair(0x5233D4, 0xB0A4FA),
        accentTint: Pair(0xEFEAFE, 0x241F3A),
        accentInk: Pair(0x4A34C9, 0xC8BDFB),
        onAccent: Pair(0xFFFFFF, 0x171528),
        ink: Pair(0x191826, 0xECE9F7),
        ink2: Pair(0x5A5772, 0xA8A4C0),
        ink3: Pair(0x6F6C88, 0x8E8AA8),
        hair: Pair(0xE7E4F2, 0x302C42),
        hair2: Pair(0xEFEDF7, 0x282539),
        controlBd: Pair(0xCBC7DB, 0x3C3852),
        surface: Pair(0xFFFFFF, 0x1B1926),
        surface2: Pair(0xFAF9FF, 0x211F2E),
        ground: Pair(0xF5F4FB, 0x121019),
        field: Pair(0xFFFFFF, 0x2E2B40),
        cardShadow: Alpha(0x241B4D, light: 0.1, dark: 0.55),
        cardShadowHover: Alpha(0x241B4D, light: 0.18, dark: 0.7),
        ok: Pair(0x0E9F6E, 0x34D399),
        okTint: Pair(0xE7F7EF, 0x12271E),
        okInk: Pair(0x07724F, 0x6EE7B7),
        draft: Pair(0xC77D16, 0xE0A355),
        draftTint: Pair(0xFBF1E0, 0x2A2113),
        draftInk: Pair(0x8A5610, 0xF0C98A),
        danger: Pair(0xDC2626, 0xF87171),
        dangerTint: Pair(0xFEF2F2, 0x2A1414),
        dangerInk: Pair(0xB91C1C, 0xFCA5A5),
        noteBg: Pair(0xECFDF5, 0x10281F),
        noteBd: Pair(0x6EE7B7, 0x2F6F52),
        noteFg: Pair(0x065F46, 0x8EE7BF),
        cautBg: Pair(0xFFFBEB, 0x2A2113),
        cautBd: Pair(0xFCD34D, 0x7A5C1E),
        cautFg: Pair(0x92400E, 0xF0C98A),
        warnBg: Pair(0xFEF2F2, 0x2A1414),
        warnBd: Pair(0xFCA5A5, 0x7A3A3A),
        warnFg: Pair(0x991B1B, 0xF6B0B0)
    )

    static let lfi = BrandPalette(
        radii: BrandRadii(panel: 8, card: 8, figure: 6, control: 5, chip: 8),
        fontFamily: "Archivo",
        fontPostScriptName: "Archivo-SemiBold",
        fontFallbacks: ["\"Helvetica Neue\"", "Helvetica", "Arial", "\"Liberation Sans\"", "sans-serif"],
        accent: Pair(0xB46B3E, 0xD58B5C),
        accentPress: Pair(0x9A5A33, 0xE3A579),
        accentTint: Pair(0xF6EDE5, 0x3A2E25),
        accentInk: Pair(0x8F5430, 0xE3A579),
        onAccent: Pair(0xFFFFFF, 0x211F1C),
        ink: Pair(0x47443E, 0xF8F4EC),
        ink2: Pair(0x6F695F, 0xCFC7B8),
        ink3: Pair(0x756C5C, 0xB5AA99),
        hair: Pair(0xD8D2C6, 0x4A463F),
        hair2: Pair(0xE7E2D7, 0x3F3C36),
        controlBd: Pair(0xC9C1B3, 0x686258),
        surface: Pair(0xFFFFFF, 0x3A3833),
        surface2: Pair(0xFAF8F3, 0x43403A),
        ground: Pair(0xF5F2EB, 0x2F2D29),
        field: Pair(0xFFFFFF, 0x4A4740),
        cardShadow: Alpha(0x47443E, light: 0.1, dark: 0.55),
        cardShadowHover: Alpha(0x47443E, light: 0.18, dark: 0.7),
        ok: Pair(0x3E7D5A, 0x6FB089),
        okTint: Pair(0xE9F1EB, 0x23302A),
        okInk: Pair(0x2B5B40, 0x9BCEB1),
        draft: Pair(0xC79A72, 0xD5AE89),
        draftTint: Pair(0xF7EFE6, 0x332A21),
        draftInk: Pair(0x8A5F35, 0xE0C09E),
        danger: Pair(0x9D3F32, 0xC96253),
        dangerTint: Pair(0xF7EAE7, 0x33211E),
        dangerInk: Pair(0x7F3227, 0xE0897B),
        noteBg: Pair(0xE9F1EB, 0x23302A),
        noteBd: Pair(0x3E7D5A, 0x6FB089),
        noteFg: Pair(0x2B5B40, 0x9BCEB1),
        cautBg: Pair(0xF7EFE6, 0x332A21),
        cautBd: Pair(0xC79A72, 0xD5AE89),
        cautFg: Pair(0x8A5F35, 0xE0C09E),
        warnBg: Pair(0xF7EAE7, 0x33211E),
        warnBd: Pair(0xC97F72, 0xC96253),
        warnFg: Pair(0x7F3227, 0xE0897B)
    )
}
