#!/usr/bin/env swift
// Emit the macOS brand palettes from `contract/brand.json`.
//
//   swift Scripts/gen-brand.swift            # write the file
//   swift Scripts/gen-brand.swift --check    # fail if it is stale (what CI runs)
//
// `contract/brand.json` is THE brand contract and is identical in this repo and
// in Armadillon44/shotAI. Every drift found in the 2026-09-14 cross-check was a
// single value edited on one side and not the other; a table that is generated
// from one file cannot drift that way.
//
// Foundation only, no package, no dependency — it runs from a clean checkout.
import CryptoKit
import Foundation

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let specURL = root.appendingPathComponent("contract/brand.json")
let outURL = root.appendingPathComponent("Packages/ShotModel/Sources/ShotModel/BrandPalette+Generated.swift")
let check = CommandLine.arguments.contains("--check")

func die(_ m: String) -> Never {
    FileHandle.standardError.write("gen-brand: \(m)\n".data(using: .utf8)!)
    exit(1)
}

guard let data = try? Data(contentsOf: specURL),
      let spec = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
else { die("cannot read \(specURL.path)") }

guard let brands = spec["brands"] as? [String: Any],
      let platforms = spec["platforms"] as? [String: Any],
      let macos = platforms["macos"] as? [String: Any],
      let members = macos["members"] as? [[String: String]]
else { die("malformed spec") }

/// `6` or `{"macos": 6, "windows": 8}` — a value the platforms have not agreed on
/// is carried as an object so generation stays a no-op while the disagreement
/// stays visible. Resolving one collapses it to a plain number.
func platformValue(_ any: Any?) -> Any? {
    if let o = any as? [String: Any] { return o["macos"] }
    return any
}

func hexLiteral(_ s: String, _ where_: String) -> String {
    let h = s.hasPrefix("#") ? String(s.dropFirst()) : s
    guard h.count == 6, UInt32(h, radix: 16) != nil else {
        die("\(where_): expected 6-digit #rrggbb, got \"\(s)\"")
    }
    return "0x" + h.uppercased()
}

func num(_ any: Any?) -> String {
    guard let d = any as? Double ?? (any as? Int).map(Double.init) else { return "nil" }
    return d == d.rounded() ? String(Int(d)) : String(d)
}

// MARK: - Invariants
//
// Checked at GENERATION time, so a palette that breaks one cannot be committed.
// This is the half that matters: the fix for a bad value is a commit, the fix for
// a whole CLASS of bad value is a rule.
for inv in (spec["invariants"] as? [[String: Any]] ?? []) {
    guard (inv["rule"] as? String) == "distinct",
          let mode = inv["mode"] as? String,
          let toks = inv["tokens"] as? [String], toks.count == 2 else { continue }
    for (bname, braw) in brands {
        guard let b = braw as? [String: Any], let cols = b["colors"] as? [String: Any],
              let a = (cols[toks[0]] as? [String: Any])?[mode] as? String,
              let c = (cols[toks[1]] as? [String: Any])?[mode] as? String else { continue }
        if a == c {
            die("""
                invariant violated — \(bname).\(mode): \(toks[0]) and \(toks[1]) are both \(a).
                  \(inv["why"] as? String ?? "")
                """)
        }
    }
}

// MARK: - Emit

// The contract's content hash, stamped into the header. The same file lives in
// Armadillon44/shotAI and its generated table carries the same line, so "the two
// repos hold the same contract" is checkable by eye instead of asserted in prose.
let specHash = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()

var out = """
// GENERATED by Scripts/gen-brand.swift from contract/brand.json — DO NOT EDIT.
// contract sha256: \(specHash)
//
// Change a colour in contract/brand.json and regenerate; the same file drives
// src/shared/brand-colors.generated.ts in Armadillon44/shotAI, so the two
// platforms cannot disagree about a value neither of them owns.
//
// The struct, its documentation and everything about how these are CONSUMED
// live in BrandPalette.swift, by hand. Only the table is generated.

public extension BrandPalette {\n
"""

for bname in ["shotAI", "lfi"] {
    guard let b = brands[bname] as? [String: Any],
          let cols = b["colors"] as? [String: Any],
          let alphas = b["alpha"] as? [String: Any],
          let radii = b["radii"] as? [String: Any],
          let font = b["font"] as? [String: Any]
    else { die("brand \(bname) missing or malformed") }

    func pair(_ n: String) -> String {
        guard let p = cols[n] as? [String: Any],
              let l = p["light"] as? String, let d = p["dark"] as? String
        else { die("\(bname): no colour \"\(n)\" in the contract") }
        return "Pair(\(hexLiteral(l, "\(bname).\(n).light")), \(hexLiteral(d, "\(bname).\(n).dark")))"
    }

    let fallbacks = (font["fallbacks"] as? [String] ?? [])
        .map { "\"\($0.replacingOccurrences(of: "\"", with: "\\\""))\"" }
        .joined(separator: ", ")
    func str(_ any: Any?) -> String {
        guard let s = any as? String else { return "nil" }
        return "\"\(s)\""
    }

    out += "    static let \(bname) = BrandPalette(\n"
    out += "        radii: BrandRadii(panel: \(num(platformValue(radii["panel"]))), "
    out += "card: \(num(platformValue(radii["card"]))), "
    out += "figure: \(num(platformValue(radii["figure"]))), "
    out += "control: \(num(platformValue(radii["control"]))), "
    out += "chip: \(num(platformValue(radii["chip"])))),\n"
    out += "        fontFamily: \(str(font["family"])),\n"
    out += "        fontPostScriptName: \(str(font["postScriptName"])),\n"
    out += "        fontFallbacks: [\(fallbacks)],\n"
    for m in members {
        guard let n = m["name"], let kind = m["kind"] else { die("malformed member") }
        switch kind {
        case "pair":
            out += "        \(n): \(pair(n)),\n"
        case "alpha":
            guard let a = alphas[n] as? [String: Any], let rgb = a["rgb"] as? String
            else { die("\(bname): no alpha \"\(n)\" in the contract") }
            out += "        \(n): Alpha(\(hexLiteral(rgb, "\(bname).\(n)")), "
            out += "light: \(a["light"] ?? 0), dark: \(a["dark"] ?? 0)),\n"
        default:
            die("unknown member kind \"\(kind)\"")
        }
    }
    out = String(out.dropLast(2)) + "\n    )\n"
    if bname != "lfi" { out += "\n" }
}
out += "}\n"

if check {
    let existing = (try? String(contentsOf: outURL, encoding: .utf8)) ?? ""
    if existing != out {
        die("""
            \(outURL.lastPathComponent) is STALE.
            Run `swift Scripts/gen-brand.swift` and commit the result.
            """)
    }
    print("gen-brand: up to date")
} else {
    try! out.write(to: outURL, atomically: true, encoding: .utf8)
    print("gen-brand: wrote \(outURL.lastPathComponent)")
}
